services:
  "proxy":
    secrets:
      - hashauth_crt_key

secrets:
  hashauth_crt_key:
    file: /home/hashauth/secrets/production/hashauth.io.key
  db_password:
    file: /home/hashauth/secrets/production/db_password
  db_connection_string:
    file: /home/hashauth/secrets/production/db_connection_string
  db_encryption_key:
    file: /home/hashauth/secrets/production/db_encryption_key
  jwt_private_key:
    file: /home/hashauth/secrets/production/jwt_private_key
